#!/bin/sh
# Copyright 2014 Frank Pavageau
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $# = 0 ]; then
  echo "Usage: pmpidstat PID [DELAY [COUNT]]"
  exit 1
fi

PID=$1
shift

DELAY=1
COUNT=0
if [ $# != 0 ]; then
  DELAY=$1
  shift
  if [ $# != 0 ]; then
    COUNT=$1
    shift
  fi
fi

STAT=/proc/$PID/stat
I=0
while [ -f $STAT ]; do
  echo $(date +%s) $(cat $STAT)
  I=$((I + 1))
  if [ $I = $COUNT ]; then
    break
  fi
  sleep $DELAY
done
